language: node_js
sudo: false
node_js:
  - "10"
  - "9"
  - "8"
  - "7"
cache:
  directories:
    - node_modules
notifications:
  email: false
before_install:
  - npm i mongodb-download@2.2.6
script:
  - npm run test:lint
  - npm run test:coverage
  - npm run report:coverage