language: node_js
sudo: false
node_js:
  - "9"
  - "8"
  - "7"
  - "6"
cache:
  directories:
    - node_modules
notifications:
  email: false
before_install:
  - npm i mongodb-download@2.2.3
script:
  - npm run test:lint
  - npm run test